-- AlterEnum: add OCR_EXTRACCION and TITULARIDAD_INMUEBLE to TipoCertificado
ALTER TYPE "TipoCertificado" ADD VALUE IF NOT EXISTS 'OCR_EXTRACCION';
ALTER TYPE "TipoCertificado" ADD VALUE IF NOT EXISTS 'TITULARIDAD_INMUEBLE';
